// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZxc5nkGDD6sC1N0eNSAy2ptJ7GB1Ya0g',
    appId: '1:616465545953:web:7a581f9e582b565d12d5a0',
    messagingSenderId: '616465545953',
    projectId: 'dreamerdb-b0dc4',
    authDomain: 'dreamerdb-b0dc4.firebaseapp.com',
    storageBucket: 'dreamerdb-b0dc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkkOffk8ntCV9_tyzad4E6PkbSnGfKxg',
    appId: '1:616465545953:android:25cdaa697fdbc12912d5a0',
    messagingSenderId: '616465545953',
    projectId: 'dreamerdb-b0dc4',
    storageBucket: 'dreamerdb-b0dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_15smKhUK1qSVH5SPK1kKsmOPQcACRY',
    appId: '1:616465545953:ios:7715ac03b1542e8b12d5a0',
    messagingSenderId: '616465545953',
    projectId: 'dreamerdb-b0dc4',
    storageBucket: 'dreamerdb-b0dc4.firebasestorage.app',
    iosBundleId: 'com.example.projectDreamerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw_15smKhUK1qSVH5SPK1kKsmOPQcACRY',
    appId: '1:616465545953:ios:7715ac03b1542e8b12d5a0',
    messagingSenderId: '616465545953',
    projectId: 'dreamerdb-b0dc4',
    storageBucket: 'dreamerdb-b0dc4.firebasestorage.app',
    iosBundleId: 'com.example.projectDreamerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZxc5nkGDD6sC1N0eNSAy2ptJ7GB1Ya0g',
    appId: '1:616465545953:web:0fd5f0377af81fa912d5a0',
    messagingSenderId: '616465545953',
    projectId: 'dreamerdb-b0dc4',
    authDomain: 'dreamerdb-b0dc4.firebaseapp.com',
    storageBucket: 'dreamerdb-b0dc4.firebasestorage.app',
  );
}
